gliftspec = 
{ divId: null,
  sgfCollection: 
   [ { widgetType: 'EXAMPLE',
       alias: 'sgf:0',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:1',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:2',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:3',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:4',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:5',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:6',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:7',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:8',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:9',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:10',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:11',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:12',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:13',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:14',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:15',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:16',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:17',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:18',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:19',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:20',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:21',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:22',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:23',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:24',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:25',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:26',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:27',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:0',
       initialPosition: '',
       nextMovesPath: '0.0.0.0.0.0.0.0.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:0',
       initialPosition: '',
       nextMovesPath: '0.0.0.0.1.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:0',
       initialPosition: '',
       nextMovesPath: '0.1.0.0.0.0.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:1',
       initialPosition: '',
       nextMovesPath: '0.0.0.0.0.0.0.0.0.0.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:1',
       initialPosition: '',
       nextMovesPath: '1.0.0.0.0.0.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:1',
       initialPosition: '',
       nextMovesPath: '2.0.0.0.0.0.0.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:2',
       initialPosition: '',
       nextMovesPath: '0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:2',
       initialPosition: '',
       nextMovesPath: '0.0.0.0.0.0.0.0.0.0.1.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:2',
       initialPosition: '',
       nextMovesPath: '0.0.0.0.0.0.0.0.1.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:3',
       initialPosition: '',
       nextMovesPath: '0.0.0.0.0.0.0.0.0.0.0.0.0.0.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:3',
       initialPosition: '',
       nextMovesPath: '0.0.0.0.0.0.1.0.0.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:3',
       initialPosition: '',
       nextMovesPath: '1.0.0.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:4',
       initialPosition: '',
       nextMovesPath: '0.0.0.0.0.0.0.0.0.0.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:4',
       initialPosition: '',
       nextMovesPath: '0.1.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:5',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:6',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:7',
       initialPosition: '',
       nextMovesPath: '0.0.0.0.0',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:7',
       initialPosition: '',
       nextMovesPath: '1',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:8',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:9',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:10',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:11',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:12',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:13',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:14',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:15',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:16',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:17',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:18',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:19',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:20',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:21',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:22',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:23',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:24',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:25',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:26',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] },
     { widgetType: 'EXAMPLE',
       alias: 'sgf:27',
       initialPosition: '',
       nextMovesPath: '',
       boardRegion: 'AUTO',
       metadata: [Object] } ],
  sgfMapping: 
   { 'sgf:0': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dm][fm][cn][fn][ho][jo][po][ep][qp][hq]AB[gl][gm][im][jn][kn][co][dp][lp][cq][eq][fq][kq][oq]\n(;B[go]\n(;W[fp]\n;B[gp]\n;W[gn]\n(;B[hn]\n;W[gq]\n;B[hp]\n;W[io]\n;B[ip]C[Correct])\n(;B[gq]\n;W[hn]C[White connects]))\n(;W[gn]\n;B[hn]\n;W[gp]\n;B[fo]\n;W[fp]\n;B[eo]C[Correct]))\n(;B[gn]\n;W[fp]\n;B[go]\n;W[gp]\n;B[fo]\n;W[eo]\n;B[en]\n;W[em]C[White has connected])\n(;B[fp]\n;W[go]C[White connects easily]))\n',
     'sgf:1': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[bk][el][bm][cm][dm][en][qn][do][eo][ep][eq][fq][iq][dr][ir][jr][kr][lr]AB[am][em][fm][bn][cn][dn][gn][co][io][dp][gp][ip][lp][pp][cq][dq][jq][lq][nq][cr][mr]\n(;B[fr]\n;W[er]\n;B[hr]\n;W[gr]\n;B[hq]C[Correct.  White is dead.]\n;W[fs]\n;B[ds]\n;W[hs]\n;B[is]\n;W[js]\n;B[ls]C[Continuation.])\n(;B[hr]\n;W[hq]\n;B[gq]\n;W[gr]\n;B[fr]\n;W[hs]\n;B[er]C[Successful for Black, but Black can do better.])\n(;B[gq]\n;W[gr]\n;B[er]\n;W[fr]\n(;B[ds]\n;W[hq]\n;B[hs]\n;W[is]C[White lives.])\n(;B[hq]\n;W[es]\n;B[hr]\n;W[hs]\n;B[gs]\n;W[is]C[White lives.])))\n',
     'sgf:2': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[ql][cm][bn][co][bp][cp][np][dq][nq][dr][fr][es]AB[om][cn][dn][pn][do][dp][jp][pp][cq][eq][oq][er]\n(;B[cr]\n;W[ds]\n;B[fq]\n(;W[gr]\n(;B[fs]\n;W[gs]\n;B[cs]\n;W[fs]\n(;B[gq]\n;W[hr]\n(;B[ir]\n;W[hq]\n;B[hp]\n;W[iq]\n;B[jq]\n;W[jr]\n;B[is]\n;W[js]\n;B[ip]\n;W[hs]\n;B[is]\n;W[ir]\n;B[kr]C[Correct])\n(;B[iq]\n;W[bq]C[Black\'s still behind in the capturing race.]))\n(;B[hq]\n;W[bq]C[Black can\'t win the capturing race]))\n(;B[gq]\n;W[cs]\n;B[hr]\n;W[br]\n;B[gs]\n;W[bq]LB[gq:A][cs:B]C[Not as good for Black. Black should play B before A.]))\n(;W[cs]\n;B[gr]\n;W[br]\n;B[fs]\n;W[bq]C[Correct.  This is the best option for White.]))\n(;B[fq]\n;W[cr]\n;B[gr]\n;W[fs]\n;B[gs]\n;W[ds]\n;B[gq]C[Black loses sente and White connects.  Black can get a better result.]))\n',
     'sgf:3': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[ik][kk][lk][ok][qk][dl][ll][cm][pm][dn][on][lo][mo][no][po][ep][gp][ip][mp][qp][fq][kq][mq][qq]AB[kl][im][km][mm][om][bn][cn][kn][mn][cp][lp][np][dq][eq][lq][nq][pq][kr][mr][or][qr][ls]\n(;B[jp]\n;W[kp]\n;B[jq]\n;W[lr]\n;B[lq]\n;W[jr]\n(;B[iq]C[Correct.]\n;W[ir]\n;B[hq]\n;W[hr]\n;B[hp]\n;W[io]\n;B[ho]\n;W[gq]\n;B[jl]C[Continuation.])\n(;B[ir]\n;W[jo]\n;B[iq]\n;W[io]C[Black can\'t connect now.]))\n(;B[kp]\n;W[ko]\n;B[jo]\n;W[jp]C[Black is cut in two])\n(;B[jq]\n;W[jp]\n;B[kp]\n;W[ko]C[Black can\'t connect.])\n(;B[jo]\n;W[kp]C[Black can\'t connect this way.]))\n',
     'sgf:4': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[nk][nl][pl][lm][mm][ln][qn][gp][rp][lq][rq]AB[cj][ll][ml][km][nm][dn][nn][dp][np][pp][qq]\n;B[lp]\n(;W[kp]\n;B[lo]\n;W[kn]\n;B[ko]\n;W[kl]\n;B[jn]\n;W[jm]\n;B[jp]\n;W[kq]\n;B[jq])\n(;W[kl]\n;B[kq]))\n',
     'sgf:5': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[oj][ek][gk][ik][jk][ol][im][jm][om][in][nn][ho][gp][hp][mp][cq][dq][eq][fq][kq][oq][pq][hr][qr]AB[jj][ck][kk][kl][nl][ql][cm][km][en][gn][hn][jn][kn][pn][go][io][cp][dp][ep][fp][jp][pp][qp][jq][qq][jr][rr])\n',
     'sgf:6': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[jl][ll][dm][hm][om][on][io][oo][gp][hp][ip][jp][op][hq][kq][mq][nq][oq][kr]AB[qk][jn][ln][pn][qn][co][jo][dp][fp][kp][lp][mp][np][pp][fq][gq][iq][jq][pq][hr][jr])\n',
     'sgf:7': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dk][el][fl][cm][dm][fm][cn][gn][pn][go][bp][ep][fp][pp][cq][dq][eq]AB[dl][em][gm][hm][dn][en][fn][in][co][cp][ip][bq][fq][hq][nq][br][fr]\n(;B[bm]\n;W[bn]\n;B[bo]\n;W[cl]\n;B[do]C[Correct])\n(;B[bo]))\n',
     'sgf:8': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[cj][ej][hn][pn][co][cp][dp][fp][hp][ip][pp][fq][gq]AB[bn][cn][do][eo][fo][go][gp][jp][hq][iq][nq])\n',
     'sgf:9': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[ck][dk][ek][fk][gk][il][jl][im][gn][hn][do][go][mo][cp][fp][jp][dq][jq][mq]AB[cl][dl][el][fl][ql][gm][hm][jm][km][in][ho][jo][po][gp][ip][eq][gq][pq])\n',
     'sgf:10': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[cn][in][kn][mn][ho][mo][hp][mp][iq][kq][mq][oq][pq][qq][ir][kr][rr][is][js][rs]AB[nn][no][po][ro][dp][ip][jp][kp][np][qp][fq][hq][jq][rq][hr][jr][sr])\n',
     'sgf:11': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[pm][do][fo][qo][cp][dp][ep][gp][gq][gr]AB[cn][dn][en][co][eo][fp][op][fq][pq][er])\n',
     'sgf:12': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[fl][cm][dm][em][gm][im][bn][en][bo][co][jo][lo][no][ep][fp][op][dq][fq][nq][pq][dr][pr]AB[qk][cn][dn][fn][qn][do][eo][po][cp][dp][pp][eq][iq][lq][qq][er][fr])\n',
     'sgf:13': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dm][dn][bo][do][bp][dp][jp][np][pp][fq][iq][jq]AB[cl][dl][fl][bn][cn][in][qn][co][hp][ip][hq][hr])\n',
     'sgf:14': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[cj][dp][fp][gp][mp][pp][bq][cq][dq][eq][hq][iq][kq][lq][nq][dr]AB[qj][cn][qn][eo][fo][go][io][bp][cp][ep][jp][kp][lp][fq][jq][er][fr])\n',
     'sgf:15': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[oj][qj][go][dp][op][pp][fq][hq][iq][oq][qq][rq]AB[cj][cn][mn][qn][oo][po][ip][mp][np][qp][rp][jq][kq])\n',
     'sgf:16': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[ck][dk][fk][bl][em][hn][jn][do][eo][fo][ho][jo][bp][kp][np][pp][bq][dq][jq][kq][mq][er][fr][gr][nr]AB[qk][bm][cm][dn][qn][ao][bo][co][go][cp][fp][gp][hp][ip][jp][iq][ir][jr][kr][lr][mr])\n',
     'sgf:17': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[pn][co][dp][ep][gp][pp][bq][cq][gq]AB[go][ho][hp][dq][eq][iq][nq][cr])\n',
     'sgf:18': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dj][ij][fk][bl][cl][dl][fl][il][im][qm][dn][in][bo][co][fo][dp][ep][fp][hp][kp][pp][cq][fq][hq][nq]AB[fj][gj][gk][gl][bm][cm][dm][em][fm][gm][jm][lm][ko][lo][bp][cp][lp][bq][dq][eq][gq][dr][fr][gr][kr][mr])\n',
     'sgf:19': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[ik][jk][kk][bl][ll][ml][gm][hm][km][mm][bn][cn][dn][en][gn][kn][nn][do][io][ko][kp][np][pp][gq][hq][jq][mq][jr]AB[bk][ck][hk][qk][dl][fl][gl][hl][il][jl][kl][dm][lm][ln][qn][bo][co][lo][dp][fp][gp][jp][lp][cq][eq][kq][lq][lr])\n',
     'sgf:20': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[bk][dk][cl][bm][dm][fm][hm][jm][km][mm][dn][ln][qn][mo][no][oo][ip][lp][bq][dq][eq][fq][gq][iq][lq][br][cr][hr]AB[cm][cn][kn][co][fo][ho][io][jo][ko][lo][bp][cp][dp][ep][fp][hp][mp][np][op][pp][qp][cq][hq])\n',
     'sgf:21': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dl][fl][cm][em][en][bo][co][eo][fp][gp][jp][kp][pp][gq][iq][lq][br][er][fr][ds][es]AB[fm][gm][dn][in][qn][do][fo][go][jo][bp][ep][hp][ip][bq][cq][dq][eq][dr][cs])\n',
     'sgf:22': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[cm][en][co][eo][lo][cp][fp][gp][kp][lp][pp][bq][eq][fq][gq][hq][lq][nq][br][gr][mr][gs]AB[qn][fo][go][ko][dp][ep][hp][jp][cq][dq][iq][kq][er][fr][kr][lr])\n',
     'sgf:23': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dk][ql][cm][dm][bn][en][hn][jn][bo][eo][jo][qo][bp][dp][ep][gp][ip][kp][lp][bq][eq][fq][iq][jq][mq][fr]AB[el][em][gm][dn][fn][co][do][fo][go][ho][ko][lo][cp][fp][mp][op][cq][dq][kq][lq][pq][cr][er][mr][fs])\n',
     'sgf:24': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[cj][pn][co][fo][dp][fp][hp][pp][dq][gq][hq][iq][ir][is]AB[cn][ho][gp][ip][eq][fq][jq][nq][gr][hr][jr])\n',
     'sgf:25': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dp][lq][mq][pq][qq][rr][rs]AB[qn][mo][no][oo][ro][kp][qp][iq][kq][rq][sr])\n',
     'sgf:26': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[qk][ll][cn][nn][lo][no][mp][lq][lr]AB[nm][on][jo][oo][dp][fp][np][pp][jq][mq][nq])\n',
     'sgf:27': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[ck][dk][cl][cm][go][qo][gp][dq][gq][hr][ir]AB[dl][dm][cn][co][eo][cp][fp][op][iq][kq][pq][jr])\n' },
  sgfDefaults: { widgetType: 'EXAMPLE' },
  metadata: { specType: 'PROBLEM_BOOK' } }
