gliftspec = 
{ divId: null,
  sgfCollection: 
   [ { alias: 'sgf:0',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:1',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:2',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:3',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:4',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:5',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:6',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:7',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:8',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:9',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:10',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:11',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:12',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:13',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:14',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:15',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:16',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:17',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:18',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:19',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:20',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:21',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:22',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:23',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:24',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:25',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:26',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:27',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:28',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:29',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:30',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:31',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:32',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:33',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:34',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:35',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:36',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:37',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:38',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:39',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:40',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:41',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:42',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' },
     { alias: 'sgf:43',
       widgetType: 'STANDARD_PROBLEM',
       boardRegion: 'AUTO' } ],
  sgfMapping: 
   { 'sgf:0': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dm][fm][cn][fn][ho][jo][po][ep][qp][hq]AB[gl][gm][im][jn][kn][co][dp][lp][cq][eq][fq][kq][oq]\n;B[go]\n;W[fp]\n;B[gp]\n;W[gn]\n;B[hn]\n;W[gq]\n;B[hp]\n;W[io]\n;B[ip]C[Correct])\n',
     'sgf:1': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[bk][el][bm][cm][dm][en][qn][do][eo][ep][eq][fq][iq][dr][ir][jr][kr][lr]AB[am][em][fm][bn][cn][dn][gn][co][io][dp][gp][ip][lp][pp][cq][dq][jq][lq][nq][cr][mr]\n(;B[fr]\n;W[er]\n;B[hr]\n;W[gr]\n;B[hq]C[Correct.  White is dead.]\n;W[fs]\n;B[ds]\n;W[hs]\n;B[is]\n;W[js]\n;B[ls]C[Continuation.])\n(;B[hr]\n;W[hq]\n;B[gq]\n;W[gr]\n;B[fr]\n;W[hs]\n;B[er]C[Successful for Black, but Black can do better.]))\n',
     'sgf:2': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[ql][cm][bn][co][bp][cp][np][dq][nq][dr][fr][es]AB[om][cn][dn][pn][do][dp][jp][pp][cq][eq][oq][er]\n(;B[cr]\n;W[ds]\n;B[fq]\n(;W[gr]\n(;B[fs]\n;W[gs]\n;B[cs]\n;W[fs]\n(;B[gq]\n;W[hr]\n;B[ir]\n;W[hq]\n;B[hp]\n;W[iq]\n;B[jq]\n;W[jr]\n;B[is]\n;W[js]\n;B[ip]\n;W[hs]\n;B[is]\n;W[ir]\n;B[kr]C[Correct])\n(;B[hq]\n;W[bq]C[White can win the capturing race.]))\n(;B[gq]\n;W[cs]\n;B[hr]\n;W[br]\n;B[gs]\n;W[bq]LB[gq:A][cs:B]C[Not as good for Black. Black should play B before A.]))\n(;W[cs]\n;B[gr]\n;W[br]\n;B[fs]\n;W[bq]C[Correct.  This is the best option for White.]))\n(;B[fq]\n;W[cr]\n;B[gr]\n;W[fs]\n;B[gs]\n;W[ds]\n;B[gq]C[Black loses sente and White connects.  Black can get a better result.]))\n',
     'sgf:3': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[ik][kk][lk][ok][qk][dl][ll][cm][pm][dn][on][lo][mo][no][po][ep][gp][ip][mp][qp][fq][kq][mq][qq]AB[kl][im][km][mm][om][bn][cn][kn][mn][cp][lp][np][dq][eq][lq][nq][pq][kr][mr][or][qr][ls]\n(;B[jp]\n;W[kp]\n;B[jq]\n;W[lr]\n;B[lq]\n;W[jr]\n(;B[iq]C[Correct.]\n;W[ir]\n;B[hq]\n;W[hr]\n;B[hp]\n;W[io]\n;B[ho]\n;W[gq]\n;B[jl]C[Continuation.])\n(;B[ir]\n;W[jo]\n;B[iq]\n;W[io]C[Black can\'t connect now.]))\n(;B[kp]\n;W[ko]\n;B[jo]\n;W[jp]C[Black is cut in two])\n(;B[jq]\n;W[jp]\n;B[kp]\n;W[ko]C[Black can\'t connect.])\n(;B[jo]\n;W[kp]C[Black can\'t connect this way.]))\n',
     'sgf:4': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[nk][nl][pl][lm][mm][ln][qn][gp][rp][lq][rq]AB[cj][ll][ml][km][nm][dn][nn][dp][np][pp][qq]\n(;B[lp]\n(;W[kp]\n(;B[lo]\n;W[kn]\n;B[ko]\n;W[kl]\n(;B[jn]\n;W[jm]\n;B[jp]C[Correct])\n(;B[jp]\n;W[jn]LB[jo:A]C[Black can do better.  There is still Aji at A.]))\n(;B[ko]\n;W[lo]C[White will cut and it will be a difficult fight for Black.]\n;B[mp]\n;W[kn]\n;B[jo]\n;W[jp]\n;B[jn]\n;W[jm]\n;B[kl]\n;W[in]))\n(;W[kl]\n;B[kq]C[Correct.]))\n(;B[lo]\n;W[kn]\n;B[ko]\n;W[jn]C[Better for White.]))\n',
     'sgf:5': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[oj][ek][gk][ik][jk][ol][im][jm][om][in][nn][ho][gp][hp][mp][cq][dq][eq][fq][kq][oq][pq][hr][qr]AB[jj][ck][kk][kl][nl][ql][cm][km][en][gn][hn][jn][kn][pn][go][io][cp][dp][ep][fp][jp][pp][qp][jq][qq][jr][rr]\n;B[no]\n;W[mo]\n;B[np]\n(;W[mn]\n(;B[mq]\n;W[lq]\n(;B[mr]\n;W[lr]\n;B[ls]\n;W[ks]\n;B[ms]\n;W[lp]\n;B[kr]C[Correct])\n(;B[nq]\n;W[kr]C[It looks like a strange move, but now Black is prevented from connecting.]\n;B[lp]\n;W[js]\n;B[is]\n;W[ks]\n;B[ir]\n;W[kp]\n;B[lo]\n;W[ko]\n;B[ln]\n;W[jo]\n;B[ip]\n;W[hs]))\n(;B[nq]\n;W[mq]C[White can keep Black disconnected.]\n;B[nr]\n;W[mr]))\n(;W[nq]\n;B[mn]C[Correct. White can\'t live on the bottom.]))\n',
     'sgf:6': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[jl][ll][dm][hm][om][on][io][oo][gp][hp][ip][jp][op][hq][kq][mq][nq][oq][kr]AB[qk][jn][ln][pn][qn][co][jo][dp][fp][kp][lp][mp][np][pp][fq][gq][iq][jq][pq][hr][jr]\n;B[hn]\n(;W[gn]\n;B[go]C[Correct])\n(;W[in]\n;B[im]\n;W[go]\n;B[gn]C[Correct. White can\'t escape.]))\n',
     'sgf:7': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dk][el][fl][cm][dm][fm][cn][gn][pn][go][bp][ep][fp][pp][cq][dq][eq]AB[dl][em][gm][hm][dn][en][fn][in][co][cp][ip][bq][fq][hq][nq][br][fr]\n(;B[bm]\n(;W[cl]\n;B[do]\n;W[bn]\n;B[bo]C[Correct])\n(;W[bn]\n;B[bo]\n;W[cl]\n;B[do]C[Correct]))\n(;B[bo]\n;W[do]C[White wins the capturing race.]))\n',
     'sgf:8': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[cj][ej][hn][pn][co][cp][dp][fp][hp][ip][pp][fq][gq]AB[bn][cn][do][eo][fo][go][gp][jp][hq][iq][nq]\n;B[in]\n;W[ho]\n;B[hm]\n;W[gn]\n;B[gm]\n;W[fn]\n(;B[fm]\n;W[en]\n;B[dn]\n;W[em]\n;B[el]\n;W[dm]\n;B[dl]C[Correct])\n(;B[em]\n;W[jo]\n;B[io]\n;W[jq]\n;B[kp]\n;W[ir]C[White escapes.]))\n',
     'sgf:9': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[ck][dk][ek][fk][gk][il][jl][im][gn][hn][do][go][mo][cp][fp][jp][dq][jq][mq]AB[cl][dl][el][fl][ql][gm][hm][jm][km][in][ho][jo][po][gp][ip][eq][gq][pq]\n;B[eo]\n;W[en]\n;B[fn]\n;W[fo]\n;B[ep]\n;W[fm]\n;B[fq]\n;W[fn]\n;B[dn])\n',
     'sgf:10': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[cn][in][kn][mn][ho][mo][hp][mp][iq][kq][mq][oq][pq][qq][ir][kr][rr][is][js][rs]AB[nn][no][po][ro][dp][ip][jp][kp][np][qp][fq][hq][jq][rq][hr][jr][sr]\n;B[mr]\n(;W[nr]\n;B[lq]\n;W[lr]\n;B[ks]\n;W[ls]\n;B[hs])\n(;W[lr]\n;B[ms]\n;W[nr]\n;B[ks]\n;W[ls]\n;B[hs]))\n',
     'sgf:11': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[pm][do][fo][qo][cp][dp][ep][gp][gq][gr]AB[cn][dn][en][co][eo][fp][op][fq][pq][er]\n(;B[cq]\n(;W[bq]\n;B[bp]\n;W[bo]\n;B[ap]\n;W[aq]\n;B[dq]\n;W[ao]\n;B[bp]\n;W[ap]\n;B[eq]\n;W[bp]\n;B[br]C[Correct]\n;W[cr]\n;B[bs]\n;W[bm]\n;B[fn]\n;W[go]\n;B[bn]\n;W[an]\n;B[bl]\n;W[cm]\n;B[cl]\n;W[dm]\n;B[el]C[Continuation])\n(;W[bp]\n;B[cr]C[Correct]))\n(;B[cr]\n;W[eq]\n;B[fr]\n;W[dr]\n;B[ds]\n;W[cq]C[It\'s a ko and very dangerous for Black.]))\n',
     'sgf:12': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[fl][cm][dm][em][gm][im][bn][en][bo][co][jo][lo][no][ep][fp][op][dq][fq][nq][pq][dr][pr]AB[qk][cn][dn][fn][qn][do][eo][po][cp][dp][pp][eq][iq][lq][qq][er][fr])\n',
     'sgf:13': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dm][dn][bo][do][bp][dp][jp][np][pp][fq][iq][jq]AB[cl][dl][fl][bn][cn][in][qn][co][hp][ip][hq][hr])\n',
     'sgf:14': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[cj][dp][fp][gp][mp][pp][bq][cq][dq][eq][hq][iq][kq][lq][nq][dr]AB[qj][cn][qn][eo][fo][go][io][bp][cp][ep][jp][kp][lp][fq][jq][er][fr])\n',
     'sgf:15': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[oj][qj][go][dp][op][pp][fq][hq][iq][oq][qq][rq]AB[cj][cn][mn][qn][oo][po][ip][mp][np][qp][rp][jq][kq])\n',
     'sgf:16': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[ck][dk][fk][bl][em][hn][jn][do][eo][fo][ho][jo][bp][kp][np][pp][bq][dq][jq][kq][mq][er][fr][gr][nr]AB[qk][bm][cm][dn][qn][ao][bo][co][go][cp][fp][gp][hp][ip][jp][iq][ir][jr][kr][lr][mr])\n',
     'sgf:17': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[pn][co][dp][ep][gp][pp][bq][cq][gq]AB[go][ho][hp][dq][eq][iq][nq][cr])\n',
     'sgf:18': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dj][ij][fk][bl][cl][dl][fl][il][im][qm][dn][in][bo][co][fo][dp][ep][fp][hp][kp][pp][cq][fq][hq][nq]AB[fj][gj][gk][gl][bm][cm][dm][em][fm][gm][jm][lm][ko][lo][bp][cp][lp][bq][dq][eq][gq][dr][fr][gr][kr][mr])\n',
     'sgf:19': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[ik][jk][kk][bl][ll][ml][gm][hm][km][mm][bn][cn][dn][en][gn][kn][nn][do][io][ko][kp][np][pp][gq][hq][jq][mq][jr]AB[bk][ck][hk][qk][dl][fl][gl][hl][il][jl][kl][dm][lm][ln][qn][bo][co][lo][dp][fp][gp][jp][lp][cq][eq][kq][lq][lr])\n',
     'sgf:20': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[bk][dk][cl][bm][dm][fm][hm][jm][km][mm][dn][ln][qn][mo][no][oo][ip][lp][bq][dq][eq][fq][gq][iq][lq][br][cr][hr]AB[cm][cn][kn][co][fo][ho][io][jo][ko][lo][bp][cp][dp][ep][fp][hp][mp][np][op][pp][qp][cq][hq])\n',
     'sgf:21': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dl][fl][cm][em][en][bo][co][eo][fp][gp][jp][kp][pp][gq][iq][lq][br][er][fr][ds][es]AB[fm][gm][dn][in][qn][do][fo][go][jo][bp][ep][hp][ip][bq][cq][dq][eq][dr][cs])\n',
     'sgf:22': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[cm][en][co][eo][lo][cp][fp][gp][kp][lp][pp][bq][eq][fq][gq][hq][lq][nq][br][gr][mr][gs]AB[qn][fo][go][ko][dp][ep][hp][jp][cq][dq][iq][kq][er][fr][kr][lr])\n',
     'sgf:23': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dk][ql][cm][dm][bn][en][hn][jn][bo][eo][jo][qo][bp][dp][ep][gp][ip][kp][lp][bq][eq][fq][iq][jq][mq][fr]AB[el][em][gm][dn][fn][co][do][fo][go][ho][ko][lo][cp][fp][mp][op][cq][dq][kq][lq][pq][cr][er][mr][fs])\n',
     'sgf:24': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[cj][pn][co][fo][dp][fp][hp][pp][dq][gq][hq][iq][ir][is]AB[cn][ho][gp][ip][eq][fq][jq][nq][gr][hr][jr])\n',
     'sgf:25': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dp][lq][mq][pq][qq][rr][rs]AB[qn][mo][no][oo][ro][kp][qp][iq][kq][rq][sr])\n',
     'sgf:26': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[qk][ll][cn][nn][lo][no][mp][lq][lr]AB[nm][on][jo][oo][dp][fp][np][pp][jq][mq][nq])\n',
     'sgf:27': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[ck][dk][cl][cm][go][qo][gp][dq][gq][hr][ir]AB[dl][dm][cn][co][eo][cp][fp][op][iq][kq][pq][jr])\n',
     'sgf:28': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[qj][rj][pk][om][ln][fo][go][ho][io][jo][lo][no][oo][po][cp][ep][jp][rp][fq][pq][rq][mr][nr][or]AB[ck][rk][qm][cn][en][pn][mo][qo][ro][gp][hp][ip][kp][lp][mp][np][qp][jq][nq][kr])\n',
     'sgf:29': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[gm][hm][km][lm][cn][en][fn][in][jn][mn][on][mo][po][hp][ip][jp][pp][kq][lq][qq][gr][hr][ir][kr][qr][fs][ks][ls]AB[gn][kn][go][jo][ko][cp][ep][gp][kp][lp][mp][np][gq][hq][mq][pq][er][fr][lr][mr][pr][ms])\n',
     'sgf:30': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[hm][cn][hn][jn][ln][ho][no][bp][hp][jp][lp][mp][bq][cq][fq][gq][mq][nq][qq][br][or]AB[cj][dm][gn][on][qn][bo][co][eo][go][ap][cp][dp][gp][np][op][pp][hq][iq][jq][kq][lq][oq][lr][pr])\n',
     'sgf:31': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[cl][dl][el][bm][fm][fn][eo][fo][po][ap][cp][dp][qp][bq][dq]AB[dm][dn][bo][co][do][go][bp][ep][fp][gp][mp][oq])\n',
     'sgf:32': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[cj][dn][dp][jp][pp][qp][hq][jq][lq][mq][dr][kr][lr]AB[qk][qn][jo][kp][lp][fq][kq][ir][jr])\n',
     'sgf:33': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[bl][cl][am][cm][bn][co][fo][go][ho][io][cp][ep][jp][cq][eq][kq][er][kr][cs]AB[dl][dm][cn][dn][fn][gn][bo][do][eo][dp][fp][pp][fq][hq][fr][jr][es])\n',
     'sgf:34': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[cj][cl][fl][gl][gm][bn][co][do][ho][ep][eq][hq][fr][gr]AB[fm][fn][bo][fo][bp][cp][fp][pp][dq][fq][mq][dr][er])\n',
     'sgf:35': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[gl][hl][em][fm][hm][en][jn][do][dp][fp][hp][jp][kp][eq][gq][hq][nq]AB[dl][el][fl][dm][gm][cn][gn][pn][co][go][ho][io][cp][gp][pp][cq][dq][fq])\n',
     'sgf:36': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[cl][dn][bo][do][bp][dp][gp][pp][eq][gq][jq][er][fr]AB[em][en][go][ho][cp][ep][fp][bq][cq][dq][fq][dr])\n',
     'sgf:37': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dm][em][fm][bn][cn][fo][go][bp][ep][cq][eq][fq][kq][nq][pr]AB[en][pn][do][eo][dp][fp][gp][jp][pp][dq][jq][jr])\n',
     'sgf:38': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[dk][cm][dm][qm][qo][dp][ep][cq][fq][iq][br][cr]AB[fm][cn][pn][do][eo][fo][bp][cp][op][bq][dq][pq])\n',
     'sgf:39': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[ck][ek][ol][nm][pm][cn][dn][ln][nn][eo][go][lo][ep][fp][gp][hp][ip][jp][np][eq][jq][jr]AB[ml][nl][hm][jm][km][lm][en][fn][gn][do][fo][ho][io][dp][op][qp][dq][fq][gq][hq][iq][mq][nq][oq][cr][er][ir])\n',
     'sgf:40': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[lk][mk][kl][nl][pl][km][in][pn][eo][fo][go][po][qo][dp][op][cq][dq][jq][lq][or]AB[kj][gk][ik][kk][ll][lm][qm][rm][dn][en][fn][gn][ln][qn][sn][bo][do][ro][cp][qp][bq][qq])\n',
     'sgf:41': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[km][mm][on][po][gp][jp][lp][qp][eq][iq][kq][lq][nq][pq]AB[qj][qm][do][ko][lo][mo][cp][kp][jq][oq][ir][jr])\n',
     'sgf:42': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[hj][ij][jj][kj][lj][mj][nj][kk][jl][ol][pl][hm][jm][km][cn][on][pn][mo][lp][mp][hq][iq][kq][oq][jr][or]AB[gk][hk][ik][jk][lk][mk][kl][ll][lm][nm][qm][kn][ln][qn][jo][po][dp][ip][kp][qp][pq])\n',
     'sgf:43': '(;GM[1]FF[4]CA[UTF-8]AP[CGoban:3]ST[2]\nRU[Japanese]SZ[19]KM[0.00]\nPW[White]PB[Black]AW[pn][dp][ep][fp][pp][cq][gq][cr][er]AB[lj][cn][en][cp][dq][eq][fq][nq][fr])\n' },
  sgfDefaults: { widgetType: 'STANDARD_PROBLEM' },
  metadata: { specType: 'PROBLEM_SET' } }
